version: '3.8'

services:
  keycloak-db:
    container_name: keycloak-db
    image: postgres:16.8
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jhonatan
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: jhonatan

      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false

      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      - keycloak-db
      - pgadmin
    ports:
      - "8081:8080"
    networks:
      - postgres
    command: ["start-dev"]
  
  pgadmin:
    image: dpage/pgadmin4:9.1
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - keycloak-db
    networks:
      - postgres
    volumes:
      - pgadmin:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin:

networks:
  postgres:
    driver: bridge
